export default [
  'What little thing instantly tells you that a person is good?',
  "What's something that you think you may have been the only person in the world to ever do?",
  "What do you consider the best decision you've made thus far in your life?",
  "What is the most selfish thing you do that you're okay with?",
  "What do you believe is the biggest thing that's currently holding you back from success?",
  "What's something that you would be willing to stay up all night to do?",
  'If someone were to sum you up with a phrase, what would that phrase be?',
  "Who is someone you need to contact that you haven't?",
  'What recent experience made you feel old?',
  'Have you ever had a terrible house guest? If so, what happened?',
  'What did you recently learn the hard way?',
  'Would you consider yourself decisive or indecisive?',
  'What were you most afraid of when you were younger? Do you still have that fear?',
  'If you knew you could live forever, how would you spend your days differently?',
  "Is there a part of your culture that you don't like?",
  "What's the one thing that you seem to constantly lose?",
  "What's the best comeback you've ever heard?",
  'What are the top three characteristics you feel are important for a person?',
  'If you had to name one thing that makes you stand out from others, what would that be?',
  'What is the last big goal you accomplished?',
  "What's the story behind your favorite memento?",
  "What do you like to do that's considered touristy?",
  'What food combination do you eat that makes others cringe?',
  "What's something that you completely don't understand?",
  "What's something interesting about you that few people know?",
  "What's your current biggest worry?",
  'What line from a song has had the biggest impact on you?',
  'What is the next thing you have on your to-buy list?',
  'If you had to pick a single word to describe this year so far, what would it be?',
  'What\'s your "famous person" story?',
  'What is the quickest way for you to lose respect for someone?',
  "What's your good luck charm?",
  'What photo have you recently seen that spoke to you?',
  "What's the most recent interesting conversation you had?",
  'What are you currently juggling in your life?',
  'Do you have a nightmare travel story?',
  'What do you spend too much time doing?',
  'Do you have a moment in your life you wish you could relive?',
  'What about you do you seem to get the most comments about?',
  'What thing from childhood do you still enjoy to this day?',
  "What's your favorite daily routine?",
  'Do you enjoy people watching?',
  'What is your biggest regret from the last month?',
  "What doesn't exist, but should?",
  "What is the most interesting class you've ever taken?",
  "What is something that happened to you that you can't logically explain?",
  'Have you been given any good advice lately?',
  "What's something that you know you should start, but haven't?",
  'How would you describe your sense of humor? Can you give an example?',
  'What is your favorite spice?',
  'What is your best shower thought?',
  "What is the messiest situation you've ever encountered?",
  'What challenge would you like to see your best friend take on?',
  'What do you secretly hoard?',
  'If each person had a warning label, what would yours say?',
  'What food do you have a love-hate relationship with?',
  'What is the last big goal you accomplished?',
  "What's the most difficult thing that you still do each day?",
  'What did you recently learn the hard way?',
  'Do you have something special that picks you up when you feel down? What is it?',
  'What is it that motivates yourself the most?',
  'If you were to work at a circus, what job would you choose?',
  'Have you ever had or witnessed a drop the mic moment?',
  'What about you do you seem to get the most comments about?',
  'If you had to name one thing that makes you stand out from others, what would that be?',
  "What's something interesting about you that few people know?",
  'How well do you trust your gut feelings?',
  "What's the embarrassing story that your parents used to tell others about you?",
  "What's the most amount of money you've ever found? What was the situation?",
  "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
  'If you were to devote your life to art, what type of art would that be?',
  'How much money would you need in the bank to feel comfortable to retire today?',
  'What law have you broken the most in your life?',
  "What is the next big purchase you're currently saving for?",
  "What's the way you find yourself procrastinating most?",
  'Do you have any secret hobbies?',
  'What would your dream day look like?',
  "What's the most interesting thing you have in your pockets right now?",
  'What is something that will instantly annoy you?',
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  "What's the next line to cross off your list?",
  'What is the last thing that you totally overreacted to?',
  'If you could change one thing about your family, what would it be?',
  "What do you do in secret that you're proud of?",
  "What do you wish they would teach at school that they don't?",
  "What's your current biggest worry?",
  "What do you know how to do that's useless?",
  'What or who are you always willing to make time for?',
  'What is the most recent fact you learned that surprised you?',
  "If you had the opportunity to look through someone's email without them knowing, would you?",
  "What foods did you used to like but don't anymore?",
  'What is something that you would really like to try again?',
  "What small stuff do you sweat even though you know you shouldn't?",
  'Have you been given any good advice lately?',
  'What do you think is the most useful skill to know?',
  'What is something that you absolutely will not put up with?',
  "What is the most selfish thing you do that you're okay with?",
  'How do you think your reality differs from others you know?',
  'How do you approach life?',
  "What's the best comeback you've ever heard?",
  'What do you wish you had more talent doing?',
  "What's something you find attractive that others may not?",
  "What's your knowing just enough to be dangerous story?",
  'What mode of transportation have you never tried?',
  'What do you wish you understood better?',
  "What's the best comeback you've ever heard?",
  'What do you find extremely difficult that most people find simple?',
  "What's the last thing that you gave up on? Are you happy or disappointed?",
  "Do you think you're more like your mom or your dad?",
  "What's the story behind your favorite memento?",
  'What is the most recent silly thing you did?',
  'Who was the last person you made happy and what did you do to do it?',
  'What does it mean to "live a good life" in your opinion?',
  'What animal do you think best reflects your personality?',
  "What do you believe is the biggest thing that's currently holding you back from success?",
  'What is the last big goal you accomplished?',
  'What type of exercise do you like most?',
  'What photo have you recently seen that spoke to you?',
  'What have you been thinking about lately that has kept you up at night?',
  'What have you recently found to be ironic?',
  "What do you consider to be the smartest thing you've ever done in your life so far?",
  "What is something that you don't mind waiting for?",
  "What is the most selfish thing you do that you're okay with?",
  "What's your opinion on cell phones?",
  'Do you, or did you in the past, have any strange habits?',
  'Do you have any memories before the age of five?',
  'What is something you feel is unacceptable that is still being done today?',
  'What did you learn from the last book you read?',
  'How would you describe someone who is wealthy?',
  'What is the quickest way for you to lose respect for someone?',
  'If you had to name one thing that makes you stand out from others, what would that be?',
  "What's the best compliment you ever received?",
  'Have you ever done something embarrassing around a former crush?',
  'Do you have a nightmare travel story?',
  'What line from a song has had the biggest impact on you?',
  'What do you consider the most difficult food to eat?',
  'How do you best like your ice-cream?',
  "What's something in your fridge right now that should probably be thrown out?",
  'What food have you never tried?',
  "Who is someone you need to contact that you haven't?",
  'What is the last encounter you had with a random stranger?',
  'What piece of art has had a large impact on you?',
  'What is the strangest way you met one of your friends?',
  'What are the top three characteristics you feel are important for a person?',
  'Does your family have any weird traditions?',
  'What technology advance are you looking forward to in the future?',
  'What are the top three qualities you admire in others?',
  'What do you think would be the worst thing about being famous?',
  'What or who are you always willing to make time for?',
  "Of all the things you've bought in your life, what has been the worst purchase?",
  "If you had the opportunity to look through someone's email without them knowing, would you?",
  'What the best thing that can happen in the first 5 minutes after waking up?',
  "What do you think people pretend to like when they really don't?",
  'Have you ever done something embarrassing around a former crush?',
  'Do you have a moment in your life you wish you could relive?',
  "What's the last thing that you gave up on? Are you happy or disappointed?",
  'If you were going to start your own business, what would it be?',
  "What's something about you today that the old you would find surprising?",
  "What's the biggest wager you've ever made?",
  'If you could only buy ten items at the grocery store to last the next week, what would you buy?',
  "What is the messiest situation you've ever encountered?",
  'What was the unspoken scandal in your town when growing up?',
  "What doesn't exist, but should?",
  'What are you currently doubting in your life?',
  "Is there a part of your culture that you don't like?",
  'Did you ever have a huge rival? Was the rivalry friendly or fierce?',
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  'What is something that someone does that will immediately turn you off?',
  'What have you recently found to be ironic?',
  "Have you ever been punished for something you didn't do?",
  'Have you ever had a missed connection encounter?',
  'What book or movie character can you see in your own life?',
  'Do you have a bucket list?',
  "What is something that happened to you that you can't logically explain?",
  'What do you find is the most boring part of your life at the moment?',
  'What is something immature you think your parents do?',
  'What has been your 15 minutes of fame up to this point?',
  'What\'s your "famous person" story?',
  "What's your knowing just enough to be dangerous story?",
  'Do you think you were ever part of the popular crowd?',
  "What do you consider to be the smartest thing you've ever done in your life so far?",
  'What would be the best thing about losing your hearing?',
  'How do you best like your ice-cream?',
  "What's the story behind your favorite memento?",
  'Of all the problems in the world, which one would you like to see solved first?',
  'Do you have a favorite brand?',
  "What's the best comeback you've ever heard?",
  'What is a restaurant you refuse to eat at and why?',
  'Do you remember what the first school report you wrote was about?',
  'How long did it take for you to come up with your current signature?',
  'Can you describe your personal style?',
  "What would you be really good at if it wasn't for one thing?",
  'What do you think would be the worst thing about being famous?',
  "What little thing do you do that you don't think many people notice?",
  'What type of exercise do you like most?',
  'What do you wish you had more talent doing?',
  "What's the best part of rain?",
  'What do you find attractive that others might find unusual?',
  'Have you ever been at an event that you think will one day be in history books?',
  "Is there anyone that you're wondering about and if they're okay?",
  "What's something you find attractive that others may not?",
  "What's your favorite thing to do when you're all alone?",
  "When you're by yourself, what do you usually think about?",
  'Is there anything that most people find cute that creeps you out?',
  "What was an experience you didn't think much about at the time, but it ultimately made you a stronger person?",
  'Do you believe there is only one other person in the world for you or many?',
  "What's something that you would be willing to stay up all night to do?",
  "What's something that you know that few other people know?",
  "What's your current Golden Rule when it comes to living life?",
  "What was a past passion that you can't believe you were so passionate about?",
  "What will be your go-to story when you're old?",
  'What weird thing do you do when nobody else is around?',
  "What's the last thing you complained about?",
  'What song do you secretly sing in the shower?',
  "Can you name 5 things you wouldn't do for a million dollars?",
  'Would you prefer to leave where your hometown and never come back or stay in your hometown and never be able to leave?',
  'What memory have you been thinking about a lot lately?',
  'What is the most recent silly thing you did?',
  'What\'s your "famous person" story?',
  'Does your family have any weird traditions?',
  'What was your most recent experience of going down the rabbit hole?',
  "Is there anyone that you're wondering about and if they're okay?",
  'Do you have a secret place?',
  'What can you talk about for hours?',
  'If you knew you could live forever, how would you spend your days differently?',
  'What has been your biggest financial mistake?',
  'Of all the problems in the world, which one would you like to see solved first?',
  'What is your best shower thought?',
  'What do you find extremely difficult that most people find simple?',
  'What are your top five snacks?',
  'Would the world be better or worse if superheroes existed?',
  "What do you know how to do that's useless?",
  'What is it that motivates yourself the most?',
  'Have you ever let someone else get punished for something you did?',
  "What do you like to do that's considered touristy?",
  'Do you enjoy people watching?',
  'What app or website completely changed your life?',
  "What are some things don't you understand about the opposite sex?",
  'What piece of art has had a large impact on you?',
  'What is something that you find mildly annoying, but not annoying enough to do anything about?',
  'What do you think is the most valuable resource?',
  "What's something in your fridge right now that should probably be thrown out?",
  'If you could have any person become a member of your family, who would you choose?',
  "What is the most selfish thing you do that you're okay with?",
  "What's something that you believe you'll never be able to do well?",
  'What is the last encounter you had with a random stranger?',
  'Do you remember what the first school report you wrote was about?',
  'If you had an extra hour a day that had to be allocated to one specific purpose, how would you use it?',
  'What is something you thought would be a great idea but was terrible when you actually did it?',
  "If you had the opportunity to look through someone's email without them knowing, would you?",
  'What weird thing do you do when nobody else is around?',
  'What was the situation where you laughed the hardest you ever have?',
  'What is the last encounter you had with a random stranger?',
  'What do you think is your most creative ability?',
  'If you could lock someone up and throw away the key, would you and if so, who would that be?',
  "What's the strangest thing you've ever found?",
  'What is your biggest regret from the last month?',
  'How would you describe your sense of humor? Can you give an example?',
  "What recent thing have you decided that you're completely over and done with?",
  'What technology advance are you looking forward to in the future?',
  "What do you think people pretend to like when they really don't?",
  'What is your current favorite TV show? What was it 5 years ago?',
  'Do you have any unusual fears?',
  'What destination is at the top of your list to visit?',
  'What was the last dream you can remember about?',
  'What thing from childhood do you still enjoy to this day?',
  'Do you consider yourself an introvert or an extrovert?',
  'How often do you find yourself daydreaming?',
  "What doesn't exist, but should?",
  'What song do you secretly sing in the shower?',
  "What's something that you completely don't understand?",
  'What is the last thing that you totally overreacted to?',
  'What do you wish you had learned five years before you did?',
  'What holiday do you think more people should celebrate?',
  "What do you do in secret that you're proud of?",
  'Is there any place that you have no desire to visit? Why?',
  'What is the oddest form of entertainment you enjoy?',
  'If you had to ask yourself one question to get the most information out of you, what would that question be?',
  'What recent situation was nearly a disaster, but you were able to prevent it?',
  'How difficult is it for you to try new things?',
  "What's the story behind your last rant?",
  "Who in your family can't you believe you're related to?",
  'Do you have any memories before the age of five?',
  'If someone were to sum you up with a phrase, what would that phrase be?',
  "What's the one thing that you seem to constantly lose?",
  "What's something that really happened to you but nobody would believe unless they were there?",
  "What's something that you use regularly that you wish you didn't have to?",
  "What's something that you thought you'd have already done by now, but haven't?",
  "What's stopping you?",
  'What was a situation where you literally did a doubletake?',
  'Where do you draw the line?',
  "What's your plan for surviving a zombie invasion?",
  "What's the best comeback you've ever heard?",
  'What memory have you been thinking about a lot lately?',
  'How do you best like your ice-cream?',
  'What is something you feel is unacceptable that is still being done today?',
  'In emergency situations, how do you react?',
  'What is a restaurant you refuse to eat at and why?',
  'Do you have a moment in your life you wish you could relive?',
  'Can you describe your personal style?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  "What's the most amount of money you've ever found? What was the situation?",
  "Is there anyone that you're wondering about and if they're okay?",
  'What photo have you recently seen that spoke to you?',
  "What's the best compliment you ever received?",
  'What do you love most about where you grew up?',
  'What do you remember most about your first crush?',
  'What are the top three characteristics you feel are important for a person?',
  'What part of the human face do you look at when you talk to someone?',
  'Have you ever had or witnessed a drop the mic moment?',
  "If it's raining outside, what activity do you most want to do?",
  "What's something that you completely don't understand?",
  'What is the easiest way to bring a smile to your face?',
  "What do you like to do that's traditionally considered masculine?",
  "What's your biggest first world problem?",
  'Do you have a favorite brand?',
  "What's your favorite thing to do when you're all alone?",
  "What is the best random act of kindness you've ever witnessed?",
  'What is something that will instantly annoy you?',
  'What are you currently doubting in your life?',
  'How do you approach life?',
  "Who is someone you need to contact that you haven't?",
  'What would be the best thing about losing your hearing?',
  'How do you best like your ice-cream?',
  'Do you have a nightmare travel story?',
  'Have you ever had to complain to management? Why?',
  "What is the most unique cloud you've ever seen in the sky?",
  'What is something that someone does that will immediately turn you off?',
  'Have you ever had a terrible house guest? If so, what happened?',
  'How long do you think you could survive on your own?',
  'What uncommon thing would you encourage everyone to try once?',
  "Why haven't you done it yet?",
  'If you had to describe your current life as a movie, which movie would you choose?',
  'What do you think is the most valuable resource?',
  "What is the next big purchase you're currently saving for?",
  'What book or movie character can you see in your own life?',
  'If you could lock someone up and throw away the key, would you and if so, who would that be?',
  'What mode of transportation have you never tried?',
  'How many things you currently own do you think you could throw away and not notice a difference in your life?',
  'If there are 100 people, how many would be more patient than you?',
  'What country sounds interesting but you know very little about it?',
  "What's the next line to cross off your list?",
  "What's your plan for surviving a zombie invasion?",
  "What's a situation when you look back you should have gone ahead and done it?",
  'If you could change one thing about your family, what would it be?',
  "What is the messiest situation you've ever encountered?",
  'What do you like best about yourself?',
  "Who in your family can't you believe you're related to?",
  'Have you ever been at an event that you think will one day be in history books?',
  'What have you recently found to be ironic?',
  'Who have you met only one time that left a huge impression on you?',
  'What was a situation where you literally did a doubletake?',
  'What is the oddest form of entertainment you enjoy?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  "What's something that you thought you'd have already done by now, but haven't?",
  'What is the quickest way for you to lose respect for someone?',
  'If you could only ask one question to each person you meet, what would that question be?',
  "What's some small thing you recently noticed?",
  "What's the story behind your favorite memento?",
  'What little thing instantly tells you that a person is good?',
  'Do you have a reoccurring dream?',
  'What do you find is the most boring part of your life at the moment?',
  'What do you think is the most valuable resource?',
  "Why haven't you done it yet?",
  "What's the most difficult thing about being you?",
  'Are you a planner or more of a go with whatever happens when it comes to travel?',
  'If someone were to sum you up with a phrase, what would that phrase be?',
  "Do you think you're more like your mom or your dad?",
  "What's the most difficult thing that you still do each day?",
  "Is there a part of your culture that you don't like?",
  "What little thing do you do that you don't think many people notice?",
  'If there are 100 people, how many would be more patient than you?',
  'Do you remember what the first school report you wrote was about?',
  "What's your current Golden Rule when it comes to living life?",
  "What's your favorite daily routine?",
  'What smell always brings back some type of memory?',
  'Do you believe there is only one other person in the world for you or many?',
  'If you could change the color of one thing, what would it be and why?',
  'What memory have you been thinking about a lot lately?',
  'What are the top three qualities you admire in others?',
  'Why?',
  'What have you recently felt grateful for?',
  "What's an interesting fact that you recently learned?",
  'Where is the strangest place you have fallen asleep?',
  'What is the next thing you have on your to-buy list?',
  'If you were going to start your own business, what would it be?',
  'Would you consider yourself decisive or indecisive?',
  'What thing from childhood do you still enjoy to this day?',
  'If you had to walk away from one technology in your life, what would it be?',
  'Do you believe that money can make you happy?',
  "What is the assumption that people make about you that's totally wrong?",
  'What is your current go-to song to dance to when nobody is around?',
  'What food combination do you eat that makes others cringe?',
  'How difficult is it for you to try new things?',
  "What's your biggest first world problem?",
  'Would you feel comfortable showing me the photos on your phone?',
  'What was your last "ah-ha" moment?',
  "What's something that you completely don't understand?",
  "Can you name 5 things you wouldn't do for a million dollars?",
  'What destination is at the top of your list to visit?',
  'Do you have any memories before the age of five?',
  "What's your opinion on naps?",
  'Would the world be better or worse if superheroes existed?',
  'What do you remember most about your first crush?',
  'Where is the strangest place you have fallen asleep?',
  'On any given day, what do you think you spend the most time doing?',
  'How would a random stranger describe you? How accurate would that be?',
  "What's a situation when you look back you should have gone ahead and done it?",
  'What smell always brings back some type of memory?',
  "What would you be really good at if it wasn't for one thing?",
  "What's your favorite thing to do when you're all alone?",
  'How far back can you trace your family tree?',
  'If each person had a warning label, what would yours say?',
  "What would someone who doesn't know you well be most surprised about?",
  "What's the last goal you set for yourself that you accomplished?",
  "What's something that you thought you'd have already done by now, but haven't?",
  'How much money would you need in the bank to feel comfortable to retire today?',
  "What's something that was completely out-of-character that you did?",
  'What is something you thought would be a great idea but was terrible when you actually did it?',
  'What\'s your "famous person" story?',
  'Where do you draw the line?',
  'What thing from childhood do you still enjoy to this day?',
  'When you want to escape from everyone, where do you go?',
  "What's the worst accident you ever had?",
  'What little thing instantly tells you that a person is good?',
  "What's the most recent interesting conversation you had?",
  "What do you consider the best decision you've made thus far in your life?",
  "What is the next big purchase you're currently saving for?",
  "What's your opinion on social media?",
  'What was the last dream you can remember about?',
  'What do you hope to be an expert about at some point in your life?',
  'What is your opinion on tattoos?',
  "What is the next skill that you'd like to learn really well?",
  "What is the most selfish thing you do that you're okay with?",
  'What holiday do you think more people should celebrate?',
  'If you had to describe your current life as a movie, which movie would you choose?',
  'What is the quickest way for you to lose respect for someone?',
  "What do you think people pretend to like when they really don't?",
  "What do you like to do that's considered touristy?",
  'If you could have any person become a member of your family, who would you choose?',
  'What are you currently doubting in your life?',
  "What's an interesting fact that you recently learned?",
  "What's something that you know you should start, but haven't?",
  'How long does it take you to form an opinion about a person?',
  "What is the most unique cloud you've ever seen in the sky?",
  "What is the best random act of kindness you've ever witnessed?",
  "What's something interesting about you that few people know?",
  'What future year are you most looking forward to arriving?',
  'What do you like best about yourself?',
  'Do you have a dream job in mind? What would it be?',
  'If each person had a warning label, what would yours say?',
  'Without saying the category, what are your top five?',
  'If you could play a prank on any historical figure, who would you pick and what prank would you do?',
  'What photo have you recently seen that spoke to you?',
  'What have you been thinking about lately that has kept you up at night?',
  'What would your dream day look like?',
  'What do you find is the most boring part of your life at the moment?',
  'What is something that you learned from simply watching a stranger?',
  "What's something uncomfortable but you feel everyone should experience at least once in their life?",
  'What can you talk about for hours?',
  "What's an example of when you changed your mind?",
  'Where do you draw the line?',
  'What uncommon thing would you encourage everyone to try once?',
  'What is your favorite spice?',
  'Do you consider telling white lies to be okay?',
  "What's your biggest first world problem?",
  "What do you consider to be the smartest thing you've ever done in your life so far?",
  'What do you wish you understood better?',
  'Would you feel comfortable showing me the photos on your phone?',
  'If you could change one thing about your family, what would it be?',
  'What is the last big argument you go into and who was it with?',
  'What old school skill set do you have?',
  'What do you find extremely difficult that most people find simple?',
  "What's something that you think you may have been the only person in the world to ever do?",
  "What's your opinion on social media?",
  "What's the one thing that you seem to constantly lose?",
  "What is something you predict will exist in 10 years that doesn't today?",
  "What's the best comeback you've ever heard?",
  "Where's the next place you want to visit?",
  'What situation is sure to make you cry?',
  "Do you have any apps on your phone that you've never used?",
  "What is something that you don't mind waiting for?",
  'What do you secretly hoard?',
  'What do you spend too much time doing?',
  'What food do you have a love-hate relationship with?',
  'Do you name inanimate objects?',
  'What have you recently felt grateful for?',
  'What do you see happening in your future?',
  "What's your close call story?",
  'If you could only ask one question to each person you meet, what would that question be?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  "What's something that you recently learned that everyone else already knew?",
  "What do you consider the best decision you've made thus far in your life?",
  'What was the last dream you can remember about?',
  "What's the most amount of money you've ever found? What was the situation?",
  "What's something that you know you should start, but haven't?",
  'How long do you think you could survive on your own?',
  'What song currently speaks to you the most?',
  'Do you think you were ever part of the popular crowd?',
  'What was the last big mistake you made?',
  "What do you like to do that's considered touristy?",
  'What is your best shower thought?',
  'What do you consider the most difficult food to eat?',
  "What is the funniest false thing you were able to convince others that's true?",
  'What song currently speaks to you the most?',
  'Do you name inanimate objects?',
  "What's the most difficult choice you were asked to make?",
  'What has been your 15 minutes of fame up to this point?',
  "What's your favorite thing to do when you're all alone?",
  'In emergency situations, how do you react?',
  "What do you do in secret that you're proud of?",
  'If you had to ask yourself one question to get the most information out of you, what would that question be?',
  "What is the best random act of kindness you've ever witnessed?",
  'What is a restaurant you refuse to eat at and why?',
  'How many things you currently own do you think you could throw away and not notice a difference in your life?',
  'How much damage could your best friend do to you if you ever had a falling out?',
  'What do you spend too much time doing?',
  'If you could change the color of one thing, what would it be and why?',
  'Can you explain love?',
  "What's the most interesting conversation you eavesdropped on?",
  "What's your opinion on social media?",
  "What's something others purchase that you simply can't understand why?",
  'What was the last meltdown that you witnessed?',
  "Of all the things you've bought in your life, what has been the worst purchase?",
  'What have you recently felt grateful for?',
  "What's something in your fridge right now that should probably be thrown out?",
  'If you had to wear a hat for the next week, what type of hat would you choose?',
  "What's the most uncomfortable situation you've ever found yourself in?",
  "What's the story about the last time you cried?",
  'Have you ever seen a movie that you thought was better than the book?',
  "What's something that you think you may have been the only person in the world to ever do?",
  "Where is the last place you've been where you felt completely out of place?",
  'If you had to pick a single word to describe this year so far, what would it be?',
  "What do you believe is the biggest thing that's currently holding you back from success?",
  'Do you believe that money can make you happy?',
  "What's some small thing you recently noticed?",
  'What obscure interest do you have?',
  'How well do you trust your gut feelings?',
  'Have you ever had a terrible house guest? If so, what happened?',
  "What is the next skill that you'd like to learn really well?",
  'Are you currently where you want to be in life?',
  'What do you wish you understood better?',
  'What technology advance are you looking forward to in the future?',
  "What is the most recent life lesson you've learned?",
  'Is there anything that makes you far angrier than it should?',
  'What food combination do you eat that makes others cringe?',
  "What's your favorite room in your house and why?",
  'What do you wish you had spent more time doing when you were younger?',
  'Without saying the category, what are your top five?',
  'What line from a song has had the biggest impact on you?',
  'What line from a song has had the biggest impact on you?',
  'If you had to walk away from one technology in your life, what would it be?',
  "What's the one thing that you seem to constantly lose?",
  'Can you explain love?',
  'What sound will instantly melt your heart?',
  'Have you ever been at an event that you think will one day be in history books?',
  'Do you people watch? If so, where do you like to do this most?',
  "What's the story behind your favorite memento?",
  "Is there a personality trait that you'd like to adopt from one of your friends?",
  'What is something that you absolutely will not put up with?',
  "What doesn't exist, but should?",
  'What is something you thought would be a great idea but was terrible when you actually did it?',
  'What destination is at the top of your list to visit?',
  "What is the best random act of kindness you've ever witnessed?",
  'What would you do if you saw a giraffe on the side of the road?',
  'If everyone here was a color, what color would each person be?',
  "What's some small thing you recently noticed?",
  'If you were to devote your life to art, what type of art would that be?',
  'What is the most recent silly thing you did?',
  'What bad decision did you make that actually turned out to be a good decision?',
  'What is your favorite spice?',
  "What's your biggest first world problem?",
  "Is there a part of your culture that you don't like?",
  'Have you ever had or witnessed a drop the mic moment?',
  'What are the top three qualities you admire in others?',
  'If you could change one thing about your family, what would it be?',
  'If you were to be famous for something, what would that be?',
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  "If it's raining outside, what activity do you most want to do?",
  'Do you have a dream job in mind? What would it be?',
  'What technology advance are you looking forward to in the future?',
  'If you could choose to be famous for something, what would it be?',
  'If you could change the color of one thing, what would it be and why?',
  'What was the last big mistake you made?',
  'What thing from childhood do you still enjoy to this day?',
  'What was the best thing you learned in the past year?',
  'How would you describe someone who is wealthy?',
  "Where's the next place you want to visit?",
  "What's something that you never seem to get tired of doing?",
  'When was the last memorable sunrise you witnessed?',
  'If you knew you could live forever, how would you spend your days differently?',
  "What's your most recent passion?",
  'Do you consider yourself an introvert or an extrovert?',
  "What's stopping you?",
  "What's the last thing you did alone and you enjoyed?",
  'What do you remember most about your first crush?',
  "What small stuff do you sweat even though you know you shouldn't?",
  'How would you spend $1,000 to give the most happiness to the most number of people possible?',
  'What would your dream day look like?',
  "What's an example of when you changed your mind?",
  'If you were to devote your life to art, what type of art would that be?',
  "What's something that you recently learned that everyone else already knew?",
  "What do you believe is the biggest thing that's currently holding you back from success?",
  "What's your close call story?",
  'Would you consider yourself decisive or indecisive?',
  'What do you like best about yourself?',
  'What was the last thing that truly disappointed you?',
  'What is your biggest regret from the last month?',
  "What's something uncomfortable but you feel everyone should experience at least once in their life?",
  'What situation is sure to make you cry?',
  'What about you do you seem to get the most comments about?',
  'If you could lock someone up and throw away the key, would you and if so, who would that be?',
  "What's the strangest thing you've ever found?",
  "Who is someone you need to contact that you haven't?",
  "What's your favorite thing to do when you're all alone?",
  "Do you have a special project you're currently working on?",
  "What's the way you find yourself procrastinating most?",
  'What is something that someone does that will immediately turn you off?',
  'What is your favorite spice?',
  "What's something that you know that few other people know?",
  "What is something that happened to you that you can't logically explain?",
  "What would someone who doesn't know you well be most surprised about?",
  'What part of history do you find most interesting?',
  'What\'s your "famous person" story?',
  'What do you wish you had learned five years before you did?',
  'Where is the strangest place you have fallen asleep?',
  "What's the last goal you set for yourself that you accomplished?",
  "What's the story behind your greatest treasure?",
  'What do you think is the most useful skill to know?',
  'What do you think is the most complex aspect about yourself?',
  "What's something that was completely out-of-character that you did?",
  'If it was possible to transplant your brain to stay alive for another 100 years, would you?',
  'What do you wish you understood better?',
  'If there are 100 people, how many would be more patient than you?',
  "What's the story behind your last rant?",
  'What have you found more helpful than you ever imagined it could be?',
  'What do you hope to be an expert about at some point in your life?',
  'What is money to you?',
  'What question do you have that nobody has been able to give you a good answer to?',
  'If you could have the attention of the world for one minute, what would you say?',
  'Do you have a bucket list?',
  'Can you explain love?',
  "If you had the opportunity to look through someone's email without them knowing, would you?",
  'How difficult is it for you to try new things?',
  "What's the most amount of money you've ever found? What was the situation?",
  "What's the strangest situation you ever found yourself in?",
  'What was the last meltdown that you witnessed?',
  'Would you feel comfortable showing me the photos on your phone?',
  'What is something you feel is unacceptable that is still being done today?',
  'Does your family have any weird traditions?',
  "What's the one thing that you seem to constantly lose?",
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  'What do you wish you understood better?',
  'What little thing instantly tells you that a person is good?',
  'What do you think would be the worst thing about being famous?',
  'What types of things do you procrastinate the most on?',
  'How difficult is it for you to try new things?',
  'If you had to choose, would you rather be too hot or too cold?',
  "Can you name 5 things you wouldn't do for a million dollars?",
  'What is the most recent fact you learned that surprised you?',
  'What assumption have you made that ended up being completely incorrect?',
  'What do you remember most about your first crush?',
  "What is the next big purchase you're currently saving for?",
  'What situation is sure to make you cry?',
  'Does your family have any weird traditions?',
  'Have you ever had or witnessed a drop the mic moment?',
  "What's a situation when you look back you should have gone ahead and done it?",
  'What is a restaurant you refuse to eat at and why?',
  "Where's the next place you want to visit?",
  'What do you spend too much time doing?',
  "What's the most difficult thing about being you?",
  'What was the last meltdown that you witnessed?',
  'How long do you think you could survive on your own?',
  "What's the most amount of money you've ever found? What was the situation?",
  'What do you know is bad for you but you continue to do it anyway?',
  'What argument did you have that looking back on was absolutely ridiculous?',
  'Where was your secret hiding place as a child?',
  'What is money to you?',
  'Do you have a moment in your life you wish you could relive?',
  'When you want to escape from everyone, where do you go?',
  "When you're by yourself, what do you usually think about?",
  "What's your favorite ritual?",
  'Would you feel comfortable showing me the photos on your phone?',
  "What's something that you know you should start, but haven't?",
  'What is your current go-to song to dance to when nobody is around?',
  'What is the last big goal you accomplished?',
  "What is the funniest false thing you were able to convince others that's true?",
  "What's the strangest situation you ever found yourself in?",
  'What do you try to do to make the world a little better?',
  "If it's raining outside, what activity do you most want to do?",
  'What is something that you find mildly annoying, but not annoying enough to do anything about?',
  'What do you secretly hoard?',
  'Is there anything that most people find cute that creeps you out?',
  'What uncommon thing would you encourage everyone to try once?',
  'What are the top three qualities you admire in others?',
  'If there are 100 people, how many would be more patient than you?',
  'What question have people recently been constantly asking you?',
  "Of all the things you've bought in your life, what has been the worst purchase?",
  "What's the strangest thing you've ever found?",
  'What are your top five snacks?',
  'How difficult is it for you to try new things?',
  'If you could change the color of one thing, what would it be and why?',
  'Do you have any memories before the age of five?',
  'What bad decision did you make that actually turned out to be a good decision?',
  'Do you consider yourself an introvert or an extrovert?',
  'What smell always brings back some type of memory?',
  'What would be the best and worst part of being a cat in your opinion?',
  'What do you see happening in your future?',
  'What is something you own that you have never used?',
  'Is there any place that you have no desire to visit? Why?',
  'Is time currently passing quickly or slowly for you?',
  "What's your definition of success? Has it changed over time?",
  "Have you ever been punished for something you didn't do?",
  'Do you consider telling white lies to be okay?',
  'What do you wish you understood better?',
  "What's your story about breaking the law?",
  "What's something that you thought you'd have already done by now, but haven't?",
  'Why?',
  "What's stopping you?",
  'Have you ever had a missed connection encounter?',
  "What's the biggest wager you've ever made?",
  'If you knew you could live forever, how would you spend your days differently?',
  'What are you currently juggling in your life?',
  'What do you know is bad for you but you continue to do it anyway?',
  'Do you enjoy people watching?',
  "What's your most recent passion?",
  'Are you currently where you want to be in life?',
  "What's the most uncomfortable situation you've ever found yourself in?",
  'If you had to pick a single word to describe this year so far, what would it be?',
  'What is your opinion on tattoos?',
  'What do you find is the most boring part of your life at the moment?',
  'What old school skill set do you have?',
  'If you had to walk away from one technology in your life, what would it be?',
  "What's your good luck charm?",
  "What's something that really happened to you but nobody would believe unless they were there?",
  "What's the embarrassing story that your parents used to tell others about you?",
  "What's the story behind why you replaced the last phone you had?",
  "What's the story behind your last rant?",
  'What are your top five snacks?',
  'Have you ever been at an event that you think will one day be in history books?',
  'Do you have any secret hobbies?',
  "What's the strangest situation you ever found yourself in?",
  "Can you name 5 things you wouldn't do for a million dollars?",
  'What is the oddest form of entertainment you enjoy?',
  "What's something that you think you may have been the only person in the world to ever do?",
  "What's something commonly do today that you think people will wonder why anyone would ever do that fifty years from now?",
  'What do you wish you had learned five years before you did?',
  'What line from a song has had the biggest impact on you?',
  'Is there anything that most people find cute that creeps you out?',
  "What is the funniest false thing you were able to convince others that's true?",
  "What's the last thing you did alone and you enjoyed?",
  'What do you like best about yourself?',
  'Where do you draw the line?',
  'What is the oddest form of entertainment you enjoy?',
  'Who have you met only one time that left a huge impression on you?',
  "What's an interesting fact that you recently learned?",
  "When you're by yourself, what do you usually think about?",
  'What are your top five snacks?',
  'Where is the strangest place you have fallen asleep?',
  'What assumption have you made that ended up being completely incorrect?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  "If you were required to have a job of some type but you didn't need the money from it to survive, what job would you choose?",
  "What is the funniest false thing you were able to convince others that's true?",
  "If it's raining outside, what activity do you most want to do?",
  'Did you ever have a huge rival? Was the rivalry friendly or fierce?',
  "What's something that you would be willing to stay up all night to do?",
  'What is something that you absolutely will not put up with?',
  "What's something commonly do today that you think people will wonder why anyone would ever do that fifty years from now?",
  "What's the best comeback you've ever heard?",
  'What is the last encounter you had with a random stranger?',
  'What question do you have that nobody has been able to give you a good answer to?',
  'What do you hope to be an expert about at some point in your life?',
  'Is there any place that you have no desire to visit? Why?',
  'If you were going to start your own business, what would it be?',
  'What do you remember most about your first crush?',
  'What are you currently doubting in your life?',
  'If you could choose the way you became a hero, what would the circumstances be?',
  'When you want to escape from everyone, where do you go?',
  'How do you best like your ice-cream?',
  'What bad decision did you make that actually turned out to be a good decision?',
  "What's something that you never seem to get tired of doing?",
  "What's the most spontaneous thing you've ever done?",
  "What is socially acceptable today that you think won't be in 10 years?",
  'What or who are you always willing to make time for?',
  'What would you do if you saw a giraffe on the side of the road?',
  'What topic can you bring up at a family gathering to instantly get everyone riled up?',
  "What's the strangest situation you ever found yourself in?",
  'If you had to walk away from one technology in your life, what would it be?',
  "What's your definition of success? Has it changed over time?",
  "What is the most unique cloud you've ever seen in the sky?",
  "What's your favorite thing to do when you're all alone?",
  'What is your opinion on social media?',
  'What are you currently juggling in your life?',
  "What's something in your fridge right now that should probably be thrown out?",
  'If you knew the winning lottery numbers, would you keep them to yourself or share with others?',
  'What part of the human face do you look at when you talk to someone?',
  'What was the last meltdown that you witnessed?',
  "What was a past passion that you can't believe you were so passionate about?",
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  "What's stopping you?",
  'What can you talk about for hours?',
  "What's the story about the last time you cried?",
  'What animal do you think best reflects your personality?',
  'Do you people watch? If so, where do you like to do this most?',
  "What do you know how to do that's useless?",
  'What question have people recently been constantly asking you?',
  'Would you consider yourself decisive or indecisive?',
  'What do you find attractive that others might find unusual?',
  'If you were to be famous for something, what would that be?',
  'What was your most recent experience of going down the rabbit hole?',
  'How long does it take you to form an opinion about a person?',
  "Who is someone you recently thought about that you haven't seen or talked to in years?",
  "What's your favorite form of entertainment?",
  'What part of history do you find most interesting?',
  "What's the last goal you set for yourself that you accomplished?",
  'Have you ever had a missed connection encounter?',
  'On any given day, what do you think you spend the most time doing?',
  'How do you best like your ice-cream?',
  'If you could play a prank on any historical figure, who would you pick and what prank would you do?',
  'What old school skill set do you have?',
  'What are the top three characteristics you feel are important for a person?',
  'What weird thing do you do when nobody else is around?',
  "What's something that you know that few other people know?",
  'Have you ever let someone else get punished for something you did?',
  'How would a random stranger describe you? How accurate would that be?',
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  'What recent experience made you feel old?',
  "What's a food you vow never to eat?",
  "What's stopping you?",
  'If you were handed $500 at this moment, how would you spend it?',
  'Which of your past teachers would you like to sit down with and talk to today?',
  'What sound will instantly melt your heart?',
  'What country sounds interesting but you know very little about it?',
  'What is something you feel is unacceptable that is still being done today?',
  'What technology advance are you looking forward to in the future?',
  "What's the best compliment you ever received?",
  'What are you currently doubting in your life?',
  'What song do you secretly sing in the shower?',
  "What do you do in secret that you're proud of?",
  "What's simply too difficult?",
  "Who in your family can't you believe you're related to?",
  "What have you done that you didn't like, but would you be willing to give it another shot?",
  'Do you have a moment in your life you wish you could relive?',
  'What challenge would you like to see your best friend take on?',
  "Is there a personality trait that you'd like to adopt from one of your friends?",
  'What is your opinion on tattoos?',
  'Have you ever done something embarrassing around a former crush?',
  'What would your dream day look like?',
  'Without saying the category, what are your top five?',
  "Do you have a special project you're currently working on?",
  'What is the last thing that you totally overreacted to?',
  'What is something that you learned from simply watching a stranger?',
  "What's something others purchase that you simply can't understand why?",
  "What's the next line to cross off your list?",
  'What is your current go-to song to dance to when nobody is around?',
  'If you were to work at a circus, what job would you choose?',
  "What's the most difficult thing about being you?",
  'What photo have you recently seen that spoke to you?',
  'What do you wish you had spent more time doing when you were younger?',
  "Do you think you're more like your mom or your dad?",
  'What was the situation where you laughed the hardest you ever have?',
  "What's the best trick someone has ever played on you?",
  "What do you know how to do that's useless?",
  'If you had to pick a single word to describe this year so far, what would it be?',
  "What's your most recent passion?",
  'Is there any place that you have no desire to visit? Why?',
  'What does it mean to "live a good life" in your opinion?',
  'What destination is at the top of your list to visit?',
  "What's the last thing you did alone and you enjoyed?",
  'Have you ever had a terrible house guest? If so, what happened?',
  'Have you ever seen a movie that you thought was better than the book?',
  'What holiday do you think more people should celebrate?',
  'What part of the human face do you look at when you talk to someone?',
  'What have you been thinking about lately that has kept you up at night?',
  'What was the unspoken scandal in your town when growing up?',
  'How well do you trust your gut feelings?',
  'What do you wish you had more talent doing?',
  'What was the best thing you learned in the past year?',
  "Is there anyone that you're wondering about and if they're okay?",
  "Who is someone you need to contact that you haven't?",
  'What do you think would be the worst thing about being famous?',
  'What are the top three qualities you admire in others?',
  'Are you currently going through any type of phase?',
  'If you could change the length of each day to make it perfect for you, how many hours would it be?',
  "What's the most amount of money you've ever found? What was the situation?",
  'Are you currently where you want to be in life?',
  'What was the last big mistake you made?',
  'What part of history do you find most interesting?',
  "What's your opinion on tipping?",
  'What was your most recent experience of going down the rabbit hole?',
  'What is something that will instantly annoy you?',
  "What little thing do you do that you don't think many people notice?",
  'Who have you met only one time that left a huge impression on you?',
  'What are you currently doubting in your life?',
  "What would you be really good at if it wasn't for one thing?",
  'Do you have a nightmare travel story?',
  "What's something that you think you may have been the only person in the world to ever do?",
  'What was the last thing that truly disappointed you?',
  "When you're by yourself, what do you usually think about?",
  'What is the quickest way for you to lose respect for someone?',
  'What food do you have a love-hate relationship with?',
  'Have you ever had to complain to management? Why?',
  'What types of things do you procrastinate the most on?',
  "What's something in your fridge right now that should probably be thrown out?",
  'What is something that you learned from simply watching a stranger?',
  'What do you find is the most boring part of your life at the moment?',
  'If you could choose the way you became a hero, what would the circumstances be?',
  'How long does it take you to form an opinion about a person?',
  'What assumption have you made that ended up being completely incorrect?',
  "What's something others purchase that you simply can't understand why?",
  'What do you think is the most useful skill to know?',
  "What's your go-to funny story now, but was horrendous at that moment?",
  'How long did it take for you to come up with your current signature?',
  "What is the funniest false thing you were able to convince others that's true?",
  'What challenge would you like to see your best friend take on?',
  'How many things you currently own do you think you could throw away and not notice a difference in your life?',
  "What's something that you never seem to get tired of doing?",
  "What do you consider the best decision you've made thus far in your life?",
  "What's the strangest thing you've ever found?",
  'What would be the best and worst part of being a cat in your opinion?',
  "What's something that you think you may have been the only person in the world to ever do?",
  'What have you found more helpful than you ever imagined it could be?',
  'What uncommon thing would you like to see become more common?',
  'What do you find attractive that others might find unusual?',
  'Who is the luckiest person you know?',
  "What's your current biggest worry?",
  "What doesn't exist, but should?",
  'Which of your past teachers would you like to sit down with and talk to today?',
  "What's the best way you've found to calm yourself when you get stressed?",
  'If you had to change the language you speak, which one would you choose?',
  'Do you have a reoccurring dream?',
  'What is something that has had a big impact on your that you observed from afar?',
  'What thing from childhood do you still enjoy to this day?',
  'Is there anything that most people find cute that creeps you out?',
  'Is there any place that you have no desire to visit? Why?',
  'If you were to devote your life to art, what type of art would that be?',
  'If each person had a warning label, what would yours say?',
  "What's the most difficult thing about being you?",
  'What song currently speaks to you the most?',
  "What's the story behind your greatest treasure?",
  'Have you ever seen a movie that you thought was better than the book?',
  'What has been your 15 minutes of fame up to this point?',
  "What's the best compliment you ever received?",
  "What's the most interesting conversation you eavesdropped on?",
  "What's the next line to cross off your list?",
  'What is the strangest way you met one of your friends?',
  "What's the way you find yourself procrastinating most?",
  'What one thing would significantly make your life better?',
  'If you could remove something that exists in this world forever, what would it be?',
  'What is your opinion on tattoos?',
  'What food have you never tried?',
  "What's something you find attractive that others may not?",
  'What uncommon thing would you encourage everyone to try once?',
  'Do you have a dream job in mind? What would it be?',
  'What do you secretly hoard?',
  'What future year are you most looking forward to arriving?',
  'What have you recently felt grateful for?',
  'Have you ever had a terrible house guest? If so, what happened?',
  "What's the one thing that you seem to constantly lose?",
  'What recent event have you seen that restored your faith in humankind?',
  'What food combination do you eat that makes others cringe?',
  'If each person had a warning label, what would yours say?',
  'Do you consider yourself an introvert or an extrovert?',
  "What's something that you think you may have been the only person in the world to ever do?",
  'What technology advance are you looking forward to in the future?',
  "What's your favorite room in your house and why?",
  "When you're by yourself, what do you usually think about?",
  'What have you found more helpful than you ever imagined it could be?',
  'What about you do you seem to get the most comments about?',
  'What recent situation was nearly a disaster, but you were able to prevent it?',
  "Are there any words that you simply can't stand?",
  "What's the most interesting thing you have in your pockets right now?",
  'What do you find extremely difficult that most people find simple?',
  'What types of things do you procrastinate the most on?',
  'What types of things do you doodle?',
  'What uncommon thing would you like to see become more common?',
  "What's the last thing that you broke and how did it happen?",
  'What would be the best thing about losing your hearing?',
  'What is the last big goal you accomplished?',
  "What's a situation when you look back you should have gone ahead and done it?",
  "What's the most recent interesting conversation you had?",
  'If you could choose to be famous for something, what would it be?',
  "What do you do in secret that you're proud of?",
  'How would you spend $1,000 to give the most happiness to the most number of people possible?',
  'Have you evet taken a long shot that worked out?',
  'What is your favorite spice?',
  "What's your current Golden Rule when it comes to living life?",
  "What's something that you know you should start, but haven't?",
  'What do you wish you had learned five years before you did?',
  'If you could choose the way you became a hero, what would the circumstances be?',
  'Can you explain love?',
  'What has been your 15 minutes of fame up to this point?',
  'Do you, or did you in the past, have any strange habits?',
  'Do you name inanimate objects?',
  'What is your opinion on tattoos?',
  'What is something you thought would be a great idea but was terrible when you actually did it?',
  'What country sounds interesting but you know very little about it?',
  'How would a random stranger describe you? How accurate would that be?',
  "What do you believe is the biggest thing that's currently holding you back from success?",
  "What little thing do you do that you don't think many people notice?",
];
